# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='word_company',
            new_name='work_company',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='word_position',
            new_name='work_position',
        ),
    ]
