# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170226_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u8bfe\u7a0b\u8f6e\u64ad\u56fe'),
        ),
    ]
